const data = [
  {
    id: 1,
    cat: "Popular",
    title: "React.js",
    info: "AnyChart helps you to achieve your software development and ultimately, your business goals. We give you the most advanced, best designed and best supported solutions available. We are constantly enhancing our products with new features",
    link: "https://www.anychart.com/",
  },
  {
    id: 2,
    cat: "visualization",
    title: "D3.js",
    info: "Data-Driven Documents (D3) or D3.js is another famous JS library that developers use to document manipulation based on data. It was released in 2011 under the BSD license.",
    link: "https://d3js.org/",
  },
  {
    id: 3,
    cat: "Graphical/visualization",
    title: "Chart.js",
    info: "Chart.js is a free, open-source JavaScript library for data visualization, which supports eight chart types: bar, line, area, pie, bubble, radar, polar, and scatter.",
    link: "https://www.chartjs.org/",
  },
  {
    id: 4,
    cat: "Popular",
    title: "jQuery",
    info: "jQuery is a classic JavaScript library that’s fast, light-weight, and feature-rich. It was ,built in 2006 by John Resig at BarCamp NYC. jQuery is free and open-source software with a license from MIT.",
    link: "https://jquery.com/",
  },
  {
    id: 5,
    cat: "DataBase",
    title: "Underscore.js",
    info: "Underscore is a JavaScript utility library that provides various functions for typical programming tasks. It was created in 2009 by Jeremy Askenas and release with an MIT license. Now, Lodash has overtaken it.",
    link: "https://underscorejs.org/",
  },
  {
    id: 6,
    cat: "DataBase",
    title: "Lodash",
    info: "Lodash is also a JS utility library that makes it easier to work with numbers, arrays, strings, objects, etc. It was released in 2013 and also uses functional programming design like Underscore.js.",
    link: "https://lodash.com/",
  },
  {
    id: 7,
    cat: "visualization",
    title: "Algolia Places",
    info: "Algolia Places is a JavaScript library that provides an easy and distributed way of using address auto-completion on your site. It’s a blazingly fast and wonderfully accurate tool that can help increase your site user experience. ",
    link: "https://www.algolia.com/ref/places/",
  },
  {
    id: 8,
    cat: "animation",
    title: "Anime.js",
    info: "If you want to add animations to your site or application, Anime.js is one of the best JavaScript libraries you can find. It was released in 2019 and is lightweight with a powerful yet simple API.",
    link: "https://animejs.com/",
  },
  {
    id: 9,
    cat: "animation",
    title: "Animate On Scroll (AOS)",
    info: "Animate On Scroll works great for single-page parallax websites. This JS library is fully open-source and helps you add decent animations on your pages that look sweet as you scroll down or up",
    link: "https://michalsnik.github.io/aos/",
  },
  {
    id: 10,
    cat: "Graphical",
    title: "Bideo.js",
    info: "Do you want to incorporate full-screen videos into your site’s background? Try Bideo.js.",
    link: "https://rishabhp.github.io/bideo.js/",
  },
  {
    id: 11,
    cat: "Format",
    title: "Cleave.js",
    info: "Cleave.js offers an interesting solution if you want to format your text content. Its creation aims to provide an easier way to increase the input field’s readability by formatting the typed data.",
    link: "https://nosir.github.io/cleave.js/",
  },
  {
    id: 12,
    cat: "animation",
    title: "Choreographer.js",
    info: "Use Chreographer.js to animate complex CSS effectively. It can even add more custom functions that you can use for non-CSS animations.",
    link: "https://christinecha.github.io/choreographer-js/",
  },
];
export default data;
