const data = [
  {
    id: 1,
    cat: "Popular",
    title: "React.js",
    info: "React is a free and open-source front-end JavaScript library for building user interfaces based on UI components. It is maintained by Meta and a community of individual developers and companies.",
    link: "https://reactjs.org/",
  },
  {
    id: 2,
    cat: "visualization",
    title: "D3.js",
    info: "Data-Driven Documents (D3) or D3.js is another famous JS library that developers use to document manipulation based on data. It was released in 2011 under the BSD license.",
    link: "https://d3js.org/",
  },
  {
    id: 3,
    cat: "Graphical/visualization",
    title: "Chart.js",
    info: "Chart.js is a free, open-source JavaScript library for data visualization, which supports eight chart types: bar, line, area, pie, bubble, radar, polar, and scatter.",
    link: "https://www.chartjs.org/",
  },
  {
    id: 4,
    cat: "Popular",
    title: "jQuery",
    info: "jQuery is a classic JavaScript library that’s fast, light-weight, and feature-rich. It was ,built in 2006 by John Resig at BarCamp NYC. jQuery is free and open-source software with a license from MIT.",
    link: "https://jquery.com/",
  },
  {
    id: 5,
    cat: "DataBase",
    title: "Underscore.js",
    info: "Underscore is a JavaScript utility library that provides various functions for typical programming tasks. It was created in 2009 by Jeremy Askenas and release with an MIT license. Now, Lodash has overtaken it.",
    link: "https://underscorejs.org/",
  },
  {
    id: 6,
    cat: "DataBase",
    title: "Lodash",
    info: "Lodash is also a JS utility library that makes it easier to work with numbers, arrays, strings, objects, etc. It was released in 2013 and also uses functional programming design like Underscore.js.",
    link: "https://lodash.com/",
  },
  {
    id: 7,
    cat: "visualization",
    title: "Algolia Places",
    info: "Algolia Places is a JavaScript library that provides an easy and distributed way of using address auto-completion on your site. It’s a blazingly fast and wonderfully accurate tool that can help increase your site user experience. ",
    link: "https://www.algolia.com/ref/places/",
  },
  {
    id: 8,
    cat: "animation",
    title: "Anime.js",
    info: "If you want to add animations to your site or application, Anime.js is one of the best JavaScript libraries you can find. It was released in 2019 and is lightweight with a powerful yet simple API.",
    link: "https://animejs.com/",
  },
  {
    id: 9,
    cat: "animation",
    title: "Animate On Scroll (AOS)",
    info: "Animate On Scroll works great for single-page parallax websites. This JS library is fully open-source and helps you add decent animations on your pages that look sweet as you scroll down or up",
    link: "https://michalsnik.github.io/aos/",
  },
  {
    id: 10,
    cat: "Graphical",
    title: "Bideo.js",
    info: "Do you want to incorporate full-screen videos into your site’s background? Try Bideo.js.",
    link: "https://rishabhp.github.io/bideo.js/",
  },
  {
    id: 11,
    cat: "Formating",
    title: "Cleave.js",
    info: "Cleave.js offers an interesting solution if you want to format your text content. Its creation aims to provide an easier way to increase the input field’s readability by formatting the typed data.",
    link: "https://nosir.github.io/cleave.js/",
  },
  {
    id: 12,
    cat: "animation",
    title: "Choreographer.js",
    info: "Use Chreographer.js to animate complex CSS effectively. It can even add more custom functions that you can use for non-CSS animations.",
    link: "https://christinecha.github.io/choreographer-js/",
  },
  {
    id: 13,
    cat: "DOM rendering",
    title: "Glimmer",
    info: "Released in 2017, Glimmer features lightweight and fast UI components. It uses the powerful Ember CLI and can work with EmberJS as a component.",
    link: "https://glimmerjs.com/",
  },
  {
    id: 14,
    cat: "animations",
    title: "Granim.js",
    info: "Granim.js is a JS library that helps you create fluid and interactive gradient animations. This way, you can make your site stand out with colorful backgrounds.",
    link: "https://sarcadass.github.io/granim.js/",
  },
  {
    id: 15,
    cat: "animations",
    title: "fullPage.js",
    info: "The open-source JS library, fullPage.js, helps you create full-screen scrolling sites or one-page websites easily. It is simple to use and can also add a landscape slider inside your site sections.",
    link: "https://github.com/alvarotrigo/fullPage.js/",
  },
  {
    id: 16,
    cat: "Graphical",
    title: "Leaflet",
    info: "Leaflet is one of the best JavaScript libraries that you can use to include interactive maps into your site. It is open-source and mobile-friendly, weighing around 39kb. The MapPress Maps for WordPress plugin uses Leaflet to power its interactive maps.",
    link: "https://leafletjs.com/",
  },
  {
    id: 17,
    cat: "Graphical",
    title: "Multiple.js",
    info: "Multiple.js enables background image sharing across various elements by using CSS or HTML with no JavaScript coordinate processing.    As a result, it creates a stunning visual effect to increase more user interaction.",
    link: "https://multiple.js.org/",
  },
  {
    id: 18,
    cat: "Formating",
    title: "Moment.js",
    info: "Moment.js helps you manage time and date effectively when working with different time zones, API calls, local languages, etc.You can streamline dates and times by validating, parsing, formatting, or manipulating them.",
    link: "https://momentjs.com/",
  },
  {
    id: 19,
    cat: "Formating",
    title: "Masonry",
    info: "Masonry is an awesome JS grid layout library. This library helps you place your grid elements in suitable positions based on how much vertical space is available. It’s even used by some of the popular photo gallery WordPress plugins.",
    link: "https://masonry.desandro.com/",
  },
  {
    id: 20,
    cat: "component",
    title: "Omniscient",
    info: "Omniscient.js is a JS library that provides React component abstraction for prompt top-down rendering that embraces immutable data.    This library can help you build your project seamlessly as it is optimized and offers interesting features.",
    link: "http://omniscientjs.github.io/",
  },
  {
    id: 21,
    cat: "Forms",
    title: "Parsley",
    info: "Do you want to add forms to your projects? If yes, Parsley can be useful to you. It is an easy yet powerful JS library that you can use to validate forms.",
    link: "http://parsleyjs.org/",
  },
  {
    id: 22,
    cat: "",
    title: "Popper.js",
    info: "Popper.js was created to make it easier to position popovers, dropdowns, tooltips, and other contextual elements that appear close to a button or other similar elements. Popper provides an excellent way to arrange them, stick them to other site elements, and enable them to perform seamlessly on any screen size.",
    link: "https://popper.js.org/",
  },
  {
    id: 23,
    cat: "Graphical",
    title: "Three.js",
    info: "Three.js can make your 3-D designing delightful. It uses WebGL for rendering scenes on modern browsers. Use other CSS3, CSS2, and SVH renderers if you use IE 10 and below.",
    link: "https://threejs.org/",
  },
  {
    id: 24,
    cat: "animations",
    title: "Screenfull.js",
    info: "Use Screenfull.js to add a full-screen element to your project. Due to its impressive cross-browser efficiency, you won’t be in trouble while using this JavaScript library.",
    link: "https://github.com/sindresorhus/screenfull.js/",
  },
  {
    id: 25,
    cat: "component",
    title: "Polymer",
    info: "The open-source JavaScript library by Google – Polymer is used to build web apps using components.",
    link: "https://polymer-library.polymer-project.org/",
  },
  {
    id: 26,
    cat: "structure",
    title: "Voca",
    info: "The idea behind creating Voca is to ease out the pain while working with JavaScript strings. It comes with useful functions that make it easy to manipulate strings like changing case, pad, trim, truncate, and more.",
    link: "",
  },
];
export default data;
